MetalSage/space-stories-14

Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
Большинство людей с админ состава против + Паник просил
**Changelog**
:cl: Shegare
- remove: У ассистентов удалён доступ к техническим помещениям
<!--
:cl:
=> Удаление доступа в техи у ассистентов (пассажиров)

Resources/Prototypes/_Stories/Maps/Pools/default.yml
Выпилил Бету до переделки.
Ибо карта абсолютно ужасна, как со стороны дизайнерских решений, так и со стороны баланса и т.д.
Закомментировал карту в пуле.
<!--
:cl:
=> Beta cut before rework.

Resources/Prototypes/Loadouts/Miscellaneous/survival.yml, Resources/Prototypes/_Stories/Entities/Mobs/Player/vulpkanin.yml, Resources/Prototypes/_Stories/Entities/Mobs/Species/avali.yml, Resources/Prototypes/_Stories/Entities/Mobs/Species/felinid.yml, Resources/Prototypes/_Stories/Entities/Mobs/Species/kidan.yml, Resources/Prototypes/_Stories/Entities/Mobs/Species/rodentia.yml, Resources/Prototypes/_Stories/Voice/Vulpkanin/vulpkanin_emote_sounds.yml, Resources/Prototypes/_Stories/Voice/speech_verbs.yml
Всё в чейнджлогах
**Changelog**
:cl: Shegare
- fix: Теперь у новых рас тоже есть аварийные наборы
- fix: Киданы снова могут говорить в общий чат
- fix: Теперь новые расы должны утолять жажду и голод
<!--
:cl:
=> Fix for Stories race

Resources/Prototypes/_Stories/Catalog/Fills/Backpacks/duffelbag.yml, Resources/Prototypes/_Stories/Catalog/uplink_catalog.yml
1. Добавил вещмешок тактической одежды горничной за 6 ТК
2. Добавил собачьи уши в аплинк за 26 ТК
1. Есть в костюме хамелеона, который стоит 4 ТК. Получается дороже и бесполезнее, но зато с перчатками и банданой
2. Тот же мем что и с кошачьими ушками за 26 ТК
1. ![Content Client_gfaaPZ7TLO](https://github.com/user-attachments/assets/5d219ff8-94ac-48e0-9c98-5d5d14ee1924)
2. ![Content Client_YA4odu7rcu](https://github.com/user-attachments/assets/e0c193fe-9bae-436e-8326-e5f6cce21f96)
**Changelog**
:cl: Shegare
- add: В аплинк добавлен вещмешок тактической формы горничной за 6 ТК
- add: Собачьи уши добавлены в аплинк за 26 ТК
<!--
:cl:
- tweak: …
=> Cosmetic for uplink

Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml
* Коробка намного быстрее уходит в невидимость
* Коробка не становится видимой при движении
* У коробки появилось здоровье в 90 единиц
Умоляю, я не хочу опять таких наказаний от модерации, которые хрен предугадает новичок
**Changelog**
:cl: Shegare
- tweak: Теперь невидимая коробка обладает прочностью в 90 здоровья
- tweak: Улучшены невидимые свойства стелс-коробки
<!--
:cl:
=> Rebalance StealthBox

Resources/Prototypes/tts-voices.yml
Синхронизация списка голосов /N/TTS с эндпоинтом https://ntts.fdev.team/api/v1/tts/speakers
**Changelog**
:cl: Nonne
- add: Добавлено 70 новых голосов! Abaddon, Achemist, Anti-Mage, Arc Warden, Batrider, Bloodseeker, Bounty Hunter, Bristleback, Broodmother, Centaur Warrunner, Clinkz, Clockwerk, Crystal Maiden, Dazzle, Disruptor, Doom, Dragon Knight, Dragon Knight Dragon, Drow Ranger, Earthshaker, Ember Spirit, Enigma, Gyrocopter, Huskar, Invoker, Juggernaut, Keeper Of The Light, Kunkka, Legion Commander, Legion Commander Demon, Lich, Lina, Luna, Lycan, Lycan Wolf, Meepo, Mirana, Monkey King, Monkey King Crown, Necrophos, Nyx Assassin, Omniknight, Outworld Destroyer, Phantom Assassin, Phantom Assassin Arcana, Phantom Lancer, Pudge, Queen Of Pain, Razor, Riki, Rubick, Sand King, Shadow …
=> TTS Upstream

Resources/Locale/ru-RU/_stories/entities/objects/weapons/melee/e_sword.ftl, Resources/Prototypes/_Stories/Entities/Objects/Weapons/Melee/lightsaber.yml, Resources/Prototypes/_Stories/Loadouts/Jobs/jedi_nt.yml, Resources/Prototypes/_Stories/Loadouts/jedint_loadouts.yml
- Сделал световые мечи с предустановленным цветом: Синий, Зелёный, Жёлтый, Фиолетовый
- Добавил их в лодауты. Синий и Зелёный - открыты всегда, Жёлтый - 10 часов игры на Страже, Фиолетовый - 30 часов игры на Страже
- Вещи в лодаутах Стража сейчас открываются только за донат. Но с этими мечами будет немного приятнее наигрывать время, тем кто не тратит деньги
- Меня очень сильно попросили
**Changelog**
:cl: Shegare
- tweak: В лодауты Стража Клинка добавлены световые мечи с предустановленным цветом. Синий и Зелёный - открыты всегда, Жёлтый - 10 часов игры на Страже, Фиолетовый - 30 часов игры на Страже
<!--
:cl:
- …
=> Colored swords for loadout

Resources/Prototypes/_Stories/Loadouts/jedint_loadouts.yml
Исправил лодауты Стражу
Ебучие ST : )
**Changelog**
:cl: Shegare
- fix: Исправлены лодауты Стража Клинка
<!--
:cl:
=> HotFix jedi lodaut

Resources/Prototypes/_Stories/Entities/Clothing/OuterClothing/coats.yml
Накидка позволяет носить баллон за спиной
Забыл про эту деталь, когда откатывал баланс к нормальному виду
**Changelog**
:cl: Shegare
- tweak: Накидка позволяет носить вещи на спине
<!--
:cl:
=> Fix coat jedi

Resources/Locale/ru-RU/_stories/entities/structures/storage/canisters/gas_canisters.ftl, Resources/Locale/ru-RU/_stories/gases/gases.ftl, Resources/Locale/ru-RU/_stories/reagents/gases.ftl
БЗ -> Бизет
**Changelog**
:cl: Shegare
- tweak: БЗ переименован в Бизет
=> Fix name bz for ftl

Content.Server/_Stories/ChatFilter/ChatSystem.cs
Знак "-" больше не удаляется
Ради слов: Что-то, как-то и т.д.
Перестарался я немного...
**Changelog**
:cl: Shegare
- fix: Автозамена больше не удаляет знак "тире"
=> Fix Chat Filter

Resources/Prototypes/_Stories/Entities/Structures/Machines/printer.yml
Исправлены принтеры
**Changelog**
:cl: Shegare
- fix: Исправлены принтеры
<!--
:cl:
=> Fix printers

Content.Server/_Stories/ChatFilter/ChatSystem.cs
=> Добавление символа "\" в фильтр чата

Resources/Maps/_Stories/prison.yml
зеки -> заключённые
**Changelog**
<!--
:cl:
=> Переименовал камеры на КТ

Content.Shared/_Stories/Force/ForceSystem.cs, Content.Shared/_Stories/ForceUser/Systems/ForceUserSystem.cs, Resources/Maps/_Stories/beta.yml, Resources/Maps/_Stories/kilo.yml, Resources/Prototypes/Maps/Relic.yml, Resources/Prototypes/Maps/amber.yml, Resources/Prototypes/Maps/convex.yml, Resources/Prototypes/Maps/plasma.yml, Resources/Prototypes/_Stories/Force/presets.yml
Продолжение https://github.com/MetalSage/space-stories-14/pull/61
- В прототипах карт оффов заменил лобби роль с Юриста на АВД
- Добавил спавнер Священника на Бету
- Добавил спавнеры Научных Ассистентов на Кило (для этого пришлось мусорку и автоматы сместить на тайл влево)
- Удалил предметы запрещённые для маппинга, подчистил invalid
- Теперь дебаг ForceUser видит запас силы
- Если ForceUserSystem не может получить компонент с энтити при выдаче ForceUserComponent, то компонент удаляется, а метод возвращает return
=> Фикс интеграционных тестов

Content.Server/_Stories/Garrote/GarroteSystem.cs, Content.Shared/_Stories/Weapons/Special/Garrote/SharedGarroteSystem.cs, Resources/Locale/ru-RU/_stories/garrote/garrote-component.ftl
- Удавка работает, если жертва сидит
- Раздробил код применения удавки на методы, чтобы было понятнее какая часть за что отвечает
- Теперь для определения расстояния используется WorldPosition, вместо LocalPosition
**Changelog**
:cl: Shegare
- fix: Теперь удавка работает, если жертва сидит.
<!--
:cl:
=> Фикс удавки

Resources/Prototypes/_Stories/Entities/Objects/Fun/cards.yml
Просто добавил ST в начало айдишника
=> Фикс игральных карт

Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Stories/secret_weights.yml
- Закомментировал волшебника как игровое событие и дополнительный игровой режим
- Добавил его как игровой режим для секрета, шанс выпадения 6,3%
1) У нас ~~МРП Вьетнам~~ интересно работают спавны ивентов и из-за этого люди жалуются на волшебника, когда даже у оффов в причинах на добавление волшебника говорилось "Extremely rare antag"
2) У оффов он ещё есть как игровой режим для секрета, а у нас - нет
3) Многие проголосовали за такую идею
4) Кто знает как скоро будут починены спавны ивентов (и кто знает что они ещё будут нормально работать после "починки")
**Changelog**
:cl: Shegare
- tweak: Теперь волшебник может попасться только как отдельный игровой режим, а не как событие в середине игры.
<!-- …
=> Волшебника в отдельный игровой режим

Resources/Prototypes/_Stories/Body/Parts/kidan.yml, Resources/Prototypes/_Stories/Body/Prototypes/kidan.yml, Resources/Prototypes/_Stories/Body/Prototypes/vulpkanin.yml
Больше не криворукие
**Changelog**
:cl: Shegare
- fix: Исправлены руки вульп и киданов.
<!--
:cl:
=> Фикс рук Киданов и Вульп

Resources/Maps/_Stories/beta.yml, Resources/Maps/_Stories/kilo.yml, Resources/Maps/bagel.yml, Resources/Prototypes/_Stories/Maps/kilo.yml
- Добавил спавнпоинт науч асситентса и убрал требование в одного ранудстартого науч асситнета на Кило
- Добавил спавнпоинт АВД и Священника на Бете
- Почистил invalid
- Сделал свежие рендеры для них
=> Фикс для Bagel, Beta, Kilo

Resources/Maps/omega.yml
Спавнпоинт бригмеда и мб ещё фиксы
**Changelog**
:cl: Ceaser
- tweak: Обновлена карта Omega.
<!--
:cl:
=> Обновление Omega

Resources/Prototypes/_Stories/Maps/bagel.yml, Resources/Prototypes/_Stories/Maps/beta.yml, Resources/Prototypes/_Stories/Maps/box.yml, Resources/Prototypes/_Stories/Maps/core.yml, Resources/Prototypes/_Stories/Maps/delta.yml, Resources/Prototypes/_Stories/Maps/fland.yml, Resources/Prototypes/_Stories/Maps/kilo.yml, Resources/Prototypes/_Stories/Maps/meta.yml, Resources/Prototypes/_Stories/Maps/omega.yml
До этой ПРки нужно принять https://github.com/MetalSage/space-stories-14/pull/162 https://github.com/MetalSage/space-stories-14/pull/163
- Добавил на все карты роль Бригмедика
- Сделал их рендеры, на всякий
Давно пора
(Весит овер дохера, из-за чего сама карта в гитхаб не вмешается. Кинул ссылку с гугл облака)
https://drive.google.com/file/d/1aDZliLfvRHATDZ_mvl6BzPMqIAj44n0u/view?usp=sharing
**Changelog**
:cl: Shegare
- add: Теперь роль Бригмедика доступна на всех картах.
<!--
:cl:
=> Роль Бригмедика

Content.Server/VoiceMask/VoiceMaskSystem.cs, Content.Server/_Stories/TTS/TTSSystem.cs, Content.Server/_Stories/TTS/VoiceMaskSystem.TTS.cs, Content.Shared/Chat/SharedChatEvents.cs
Голосовая маска снова меняет ТТС.
Closes https://github.com/MetalSage/space-stories-14/issues/10
Да, немного больше хардкода, но как я не старался починить ивент, нифига не выходило (он просто не поднимается). Тем более в ивенте оффов и так передаётся имя и акцент, так что одна дополнительная переменная вряд ли сделает хуже в читабельности кода и в понимании где она передаётся
https://github.com/user-attachments/assets/0f1a987f-1621-45bd-bb47-26f6d8855e9d
**Changelog**
:cl: Shegare
- fix: Голосовая маска снова меняет ТТС.
<!--
:cl:
=> Исправление голосовой маски

Resources/Maps/_Stories/beta.yml, Resources/Maps/_Stories/kilo.yml, Resources/Maps/bagel.yml, Resources/Maps/box.yml, Resources/Maps/core.yml, Resources/Maps/meta.yml, Resources/Maps/omega.yml, Resources/Prototypes/Entities/Markers/Spawners/jobs.yml, Resources/Prototypes/_Stories/Entities/Markers/Spawners/jobs.yml, Resources/Prototypes/_Stories/Maps/bagel.yml, Resources/Prototypes/_Stories/Maps/beta.yml, Resources/Prototypes/_Stories/Maps/box.yml, Resources/Prototypes/_Stories/Maps/core.yml, Resources/Prototypes/_Stories/Maps/delta.yml, Resources/Prototypes/_Stories/Maps/fland.yml, Resources/Prototypes/_Stories/Maps/kilo.yml, Resources/Prototypes/_Stories/Maps/meta.yml, Resources/Prototypes/_Stories/Maps/omega.yml
МЕРДЖИТЬ ПОСЛЕ https://github.com/MetalSage/space-stories-14/pull/164
- Подкорректированы спанпоинты Юриста и АВД
- Добавлена роль Юриста на все карты
- Добавлены спавнпоинты АВД (рендеры не нужны)
**Changelog**
:cl: Shegare
- add: Добавлена роль Юриста.
<!--
:cl:
=> Добавление Юриста на карты

Content.Server/GameTicking/Rules/ParadoxCloneRuleSystem.cs, Resources/Prototypes/GameRules/events.yml
Парадоксальный клон Стража Клинка владеет силой, если стал клоном владельца силой
Как убить Стража без силы? Тем более лазерный меч, который он копирует, без силы использовать невозможно, а так его можно будет привязать
Если цель - Страж Клинка то накладывается ForceComponent
Пресет захордкожен, потому что его нельзя выдать через C#. Надо либо менять Serializer, либо геттер с сетером делать, в общем трогать код силы, который менять пока не особо хочется
https://github.com/user-attachments/assets/e1d360dc-11a1-45ba-928c-7c714b05233b
**Changelog**
:cl: Shegare
- tweak: Парадоксальный клон Стража Клинка также владеет силой.
<!--
:cl:
- tweak: …
=> Парадоксальный клон Стража Клинка

Resources/Prototypes/tts-voices.yml
Удаление несуществующего голоса для ТТС
=> Удаление голоса Валтос

Content.Server/_Stories/StationGoal/StationGoalPaperSystem.cs, Content.Server/_Stories/StationGoal/StationGoalPrototype.cs, Resources/Prototypes/_Stories/station_goals.yml
Теперь для каждой цели есть минимальный онлайн для её появления, чтобы при 21 онлайне не выпадала капсула колонизации
Часто на среднем-малом онлайне цели попросту не выполнялись из-за нехватки людей или ресурсов
Использовал RemoveAll
Добавил функцию IsNotEnoughPlayers для проверки условия
Без цели 0 #Сложность 0
Шаттл 40 #Сложность 3
Синга 30 #Сложность 2
Соляры 20 #Сложность 1
Артефакты 20 #Сложность 1
Орбитальное хранилище 40 #Сложность 3
Зоопарк 20 #Сложность 1
Борги 20 #Сложность 1
Капсула колонизации 40 #Сложность 3
Тесла 30 #Сложность 2
Ботаника 30 #Сложность 2
Хранилище аномалий 40 #Сложность 3
Тир 40 #Сложность 3
**Changelog**
<!--
:cl:
- tweak: Теперь более сложные цели будут выпадать …
=> Разделил цели на категории по онлайну

Resources/ServerInfo/_Stories/ServerRules/SpaceLaw/SpaceStationCrimeTable.xml
Согласовано с Астольфо, после принятия сразу сделаю на Wiki
**Changelog**
:cl: Shegare
- remove: В таблице Корпоративного Закона удалена статья 508.
=> Удаление статьи 508 из КЗ в гайдбуке

Content.Server/Standing/StandingStateController.cs
Действие вставания и падения не прерывается уроном.
Одна из причин почему механика ползанья душная - из-за того что каждый раз когда тебе сбивают вставание нужно заново нажимать кнопку, а тебе встатие сбивают даже удары кулаком. 
Это бафф для всей стан меты и меньше возможности убежать от агента, либо набегатора, который просто бросил мыло под ноги и забивает тебя, так как знает что ты не убедишь. Также это (сбивание вставания уроном) косвенный бафф толчка Стража и Инквизитора
Если что это никак не меняет баланс офов, так как у них встатие вообще моментальное
Просто doAfter не сбивается уроном
(на видео исправленные турели, но в этот ПР фикс не входит, просто для наглядности решил что лучше на турелях показать что действие не сбивается) …
=> Падение и вставание игнорирует урон

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Скафандр Бригмедика больше не замедляет скорость передвижения.
Резисты слабые, а скорость важна
**Changelog**
:cl: Shegare
- tweak: Скафандр Бригмедика больше не замедляет скорость передвижения.
<!--
:cl:
=> Бафф скафандра бригмедика

Resources/Prototypes/_Stories/Maps/beta.yml
На карте Beta теперь доступна роль борга.
**Changelog**
:cl: Shegare
- fix: На карте Beta теперь доступна роль борга.
<!--
:cl:
=> Роль борга для Беты

Content.Shared/Damage/Systems/RequireProjectileTargetSystem.cs, Content.Shared/Standing/StandingStateSystem.cs, Content.Shared/Traits/Assorted/LegsParalyzedSystem.cs
1. Откатил часть кода для упрощения апстримов
2. Больше прицельные выстрелы не нужны, чтобы попадать по лежачему (не нужно выделять мышкой, чтобы попадать пулями)
Здесь всё про второй пункт изменений. А именно механика что нужно лежачую цель выделять своим курсором для попадания проджектайлами
1. Механика с прицельным огнём интуитивно не понятная. Своим телом увеличиваешь заслоняемый проход, но почему-то это должно помогать уворачиваться от пуль. Даже кого-то забанили из-за того что модератор не знал об этой механике, что только подтверждает её мусорность и даже опасность для игроков, нежели хорошей фичей.
2. Эта механика поощряет лежачие войны, что выглядит ЛРПшно
3. Турели стреляют в сторону противника, из-за того что они не выделяют противника они никогда не могут по нему попасть. …
=> Исправление стрельбы по ползающим

Content.Shared/CCVar/CCVars.Movement.cs, Content.Shared/Movement/Systems/SharedMobCollisionSystem.cs, Content.Shared/_Stories/Weapons/Special/Garrote/GarroteComponent.cs, Resources/Prototypes/Entities/Mobs/NPCs/animals.yml, Resources/Prototypes/Entities/Mobs/NPCs/flying_animals.yml, Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml, Resources/Prototypes/Entities/Mobs/NPCs/spacetick.yml, Resources/Prototypes/_Stories/Entities/Mobs/Aliens/spaf.yml
- Коммит https://github.com/space-wizards/space-station-14/commit/f29b38c44bed6bfe9379910824287af1111ce92c придёт с апстримом (то бишь позже смерджу сюда мастер ветку)
- Отключил коллизию некоторых существ
Летающие: Дракон, Пчела, Бабочка, Ремилия, Попугай, Карпоакула (ну, все жё летать умеет)
Проползающие: Король крыс, СПАФ, Крысиный слуга, Мышь, Космический клещ, Таракан, Гамлет, Змея, Лягушка
Просто мелкие существа: Ящерица, Курица, Утка, Cлизняк (не путать со слаймом и смайлом!)
- Увеличил рендж применения удавки
Кратко о работе коллизии: она зависит от двух фикстур - fix1 и flammable. fix1 - толкает и как правило больше второй фикстуры, flammable - подвержен толканию. Менять фикстуры нельзя, так как иначе можно сделать так что существо будет проходить сквозь стены, не будет впитывать …
=> Фикс коллизии существ

Resources/Maps/_Stories/Shuttles/cargo_lima.yml, Resources/Maps/_Stories/Shuttles/emergency_lima.yml, Resources/Prototypes/_Stories/Maps/lima.yml
Изменён шаттл карго и эвака для Лимы
Не рендер, но это собственно и не карты :trollface: 
**Changelog**
:cl: samur7
- tweak: Новый шаттл эвакуации для Lima Station.
:cl: Grenski
- tweak: Новый шаттл снабжения для Lima Station.
<!--
:cl:
=> Новые шаттлы для Lima

Content.Server/_Stories/ProtectiveBubble/Components/ProtectiveBubbleComponent.cs, Content.Server/_Stories/ProtectiveBubble/Systems/ProtectiveBubbleSystem.Protect.cs, Content.Server/_Stories/ProtectiveBubble/Systems/ProtectiveBubbleSystem.cs
- Решает проблему с двойным щитом. То есть когда откатывалась возможность вызвать новый щит и при этом не теряя старый (x2 защиту можно было таким образом копить)
- Больше щит не будут нажимать раундстартом
Создал UpdateFrameTime для щитов и переменную для отслеживания оставщегося времени, до пропадения щита
(на видео поставил 10 секунд)
https://github.com/user-attachments/assets/78ebc5ff-66ff-4379-9ce9-912930d22c9b
**Changelog**
:cl: Shegare
- add: Защитный пузырь Стража Клинка больше не бесконечный. Теперь он длится 4 минуты.
<!--
:cl:
=> Длительность защитного пузыря

Content.Shared/Damage/Systems/RequireProjectileTargetSystem.cs
Обосрался в - https://github.com/MetalSage/space-stories-14/pull/183
Если упасть в крит, а после вылечиться, то пули летят сквозь тебя.
Должно работать так:
- Если крит или мёртв - Нужен прицельный огонь для попаданий
- Если жив - прицельный огонь не нужен, просто стреляешь в сторону цели
https://github.com/user-attachments/assets/2a03e9c2-ec10-4f79-bb97-19741c76c7c8
**Changelog**
:cl: Shegare
- fix: Исправлен баг из-за которого существа становились невосприимчивы к пулям.
<!--
:cl:
=> Фикс стрельбы по существам - ВАЖНО

Resources/Prototypes/_Stories/Entities/Structures/vending_machines.yml
Добавил два музмата, один станции, а другой КТ.
Ибо вещица больше для простой станции. 
Сделал старый прототип бейзом и добавил 2 прототипа на этом паренте.
- [] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре
**Changelog**
<!--
:cl:
=> Фикс МузМат-а

Resources/Locale/ru-RU/ss14-ru/prototypes/_stories/actions/types.ftl
Пофиксил локализацию виляния хвостом для вульп.
Багфикс
-
**Changelog**
<!--
:cl:
=> Fix Vulpkanin Wagging

Resources/Prototypes/GameRules/events.yml
Чувствую себя мега глупо 😃
**Changelog**
:cl: Shegare
- fix: Теперь такие события как ошибка распределения ролей и появление Инквизитора точно добавлены.
<!--
:cl:
=> Добавление игровых событий Сториса в таблицы событий

Content.Client/Administration/UI/BanPanel/BanPanel.xaml.cs, Resources/ConfigPresets/Stories/stories.toml
Изменил из среднего на высокий.
Баны у нас высокие, а сервер ставит средние, из-за чего бывают грешки от модеров.
Просто поправил строку
**Changelog**
<!--
:cl:
=> Поправка тяжести банов

Resources/Prototypes/_Stories/Objects/Tools/produce_bag.yml
=> Фикс сумки для плодов

Content.Client/Power/Battery/BatteryMenu.xaml
Немного удлинил окошко
**Changelog**
:cl:
- fix: Фикс UI СМЭС и подстанций
=> Фикс UI для СМЭС и подстанций

Resources/Locale/ru-RU/weapons/ranged/turrets.ftl
=> Исправление перевода турелей

Content.Server/GameTicking/Rules/ParadoxCloneRuleSystem.cs, Content.Shared/_Stories/ForceUser/Systems/ForceUserSystem.cs, Resources/Prototypes/GameRules/events.yml
Анхаркод выдачи силы парадоксальному клону
https://github.com/user-attachments/assets/3c0180e0-692c-435f-8038-3e44d8cdf9d7
**Changelog**
:cl: Shegare
- fix: Теперь парадоксальный клон Инквизитора получает силы Инквизитора, а не Стража.
<!--
:cl:
=> Исправление "силы" парадоксального клона

LICENSE.md
Поправил орфографическую ошибку
=> Исправление лицезнии

Resources/Locale/ru-RU/_stories/ghost-roles.ftl, Resources/Prototypes/_Stories/Entities/Markers/Spawners/ghost_roles.yml
- Теперь чтобы взять Инквиза нужно наиграть на других ролях (скопипастил время для открытия Стража)
- Почистил локализацию, изменил текст в `description`
Насчёт первого ты сам в курсе
Текст изменил так как:
1. Всё равно играют по правилам с Wiki
2. Из-за горы текста приходится окошко шире делать (что очень сильно бесит), чтобы было возможно взять роль
**Changelog**
:cl: Shegare
- tweak: Чтобы взять Инквизитора требуется наиграть время на других ролях (столько же сколько на Стража).
<!--
:cl:
=> Время открытия для Инквизитора

Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
Изменил королю крыс минд роль на свободного антага.
Сделал по вики ибо делать бедолагу антагом при живом страже - бредик.
**Changelog**
<!--
:cl:
=> Свободный король крыс 
